name: update

# daily job
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go:
          - "1.21"

        include:
          # Set the minimum Go patch version for the given Go minor
          # Usable via ${{ matrix.GO_SEMVER }}
          - go: "1.21"
            GO_SEMVER: "~1.21.0"
    runs-on: ${{ matrix.os }}
    # https://github.com/sigstore/cosign/issues/1258#issuecomment-1002251233
    # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
    permissions:
      id-token: write
      # https://docs.github.com/en/rest/overview/permissions-required-for-github-apps#permission-on-contents
      # "Releases" is part of `contents`, so it needs the `write`
      contents: write
    outputs:
      updated: ${{ steps.makever.outputs.updated }}
      dockerpath: ${{ steps.makever.outputs.dockerpath }}
      tag: ${{ steps.makever.outputs.tag }}
    steps:
      - uses: actions/checkout@master

      - name: run update script
        id: makever
        run: |
          chmod +x update.sh && ./update.sh

      - name: Install Go
        if: success() && steps.makever.outputs.updated == '1'
        uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.GO_SEMVER }}
          check-latest: true

      - name: Install xcaddy
        if: success() && steps.makever.outputs.updated == '1'
        uses: jaxxstorm/action-install-gh-release@master
        with:
          repo: caddyserver/xcaddy

      - name: Build
        if: success() && steps.makever.outputs.updated == '1'
        run: |
          xcaddy build --with github.com/xcaddyplugins/caddy-trusted-cloudfront

      - name: Release
        uses: softprops/action-gh-release@master
        if: success() && steps.makever.outputs.updated == '1'
        with:
          files: caddy
          tag_name: ${{ steps.makever.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
